
export const FILEZH = 'FILEZH'
export const FILEEN = 'FILEEN'
export const APPFILEZH = 'APPFILEZH'
export const APPFILEEN = 'APPFILEEN'
export const TEAMFILEZH = 'TEAMFILEZH'
export const TEAMFILEEN = 'TEAMFILEEN'
export const TEAMFILEKO = 'TEAMFILEKO'
export const TECHFILEZH = 'TECHFILEZH'
export const TECHFILEEN = 'TECHFILEEN'
export const JOINUSFILEZH = 'JOINUSFILEZH'
export const JOINUSFILEEN = 'JOINUSFILEEN'
export const NEWSFILEEN = 'NEWSFILEEN'
export const NEWSFILEZH = 'NEWSFILEZH'
export const NEWSFILEKO = 'NEWSFILEKO'
export const ARTICLE = 'ARTICLE'
export const ONTVIEWEN = 'ONTVIEWEN'
export const ONTVIEWZH = 'ONTVIEWZH'
export const ONTVIEWKO = 'ONTVIEWKO'
/* export const SUBSCRIBE = 'SUBSCRIBE' */

export const COOPERATIONEN = 'COOPERATIONEN'
export const COOPERATIONZH = 'COOPERATIONZH'
export const COOPERATIONKO = 'COOPERATIONKO'


export const COOPERATIONSUBMIT = 'COOPERATIONSUBMIT'

export const MAILVERFIRST = 'MAILVERFIRST'
export const GETCAPTCHA = 'GETCAPTCHA'
export const VERCAPTCHA = 'VERCAPTCHA'
export const REGISTERINDIVIDUAL = 'REGISTERINDIVIDUAL'
export const TRIONESEN = 'TRIONESEN'
export const TRIONESZH = 'TRIONESZH'
export const TRIONESLISTEN = 'TRIONESLISTEN'
export const TRIONESLISTZH = 'TRIONESLISTZH'
export const TRIONESLIST = 'TRIONESLIST'
export const KYCFAQEN = 'KYCFAQEN'
export const KYCFAQZH = 'KYCFAQZH'

export const AUDITORLOGIN = 'AUDITORLOGIN'
export const INDIVIDUALLIST = 'INDIVIDUALLIST'
export const INDIVIDUALDETAIL = 'INDIVIDUALDETAIL'
export const INDIVIDUALVERIFICATION = 'INDIVIDUALVERIFICATION'
export const INDIVIDUALFIRST = 'INDIVIDUALFIRST'
export const INDIVIDUALSECONDVERIFICATION = 'INDIVIDUALSECONDVERIFICATION'

export const NOTPASSSEARCH = 'NOTPASSSEARCH'
export const EMAILSEARCH = 'EMAILSEARCH'
export const ROWNUMBESEARECH = 'ROWNUMBESEARECH'


export const NEWSLOGIN = 'NEWSLOGIN'
export const NEWSUPLOAD = 'NEWSUPLOAD'
export const NEWSLIST = 'NEWSLIST'
export const NEWSDETAIL = 'NEWSDETAIL'
export const NEWSDELETE = 'NEWSDELETE'
export const NEWSHIDE = 'NEWSHIDE'
export const NEWSSHOW = 'NEWSSHOW'



export const PAGEDETAIL = 'PAGEDETAIL'